############################################
#          AAA_image_segmentation          #
#               Config file                #
#          Author: Bjarne Thorsted         #
#      e-mail: bthorsted@health.sdu.dk     #
############################################

appName: AAAml

# Options for modifying app behavior during runtime
Runtime:
  clean_start: false
  compute_stats: false
  compute_class_weights: false
  date_string: &date "2021-10-09" # if null, always use current date
  debug: false
  make_abundance_table: false
  run_grid_search: false
  run_train: true
  run_predict: true
  run_eval: false
  analyze: false
  create_probability_maps: false

data:
  input_ext:  "tif"
  target_ext: "png"
  data:       "/nb_projects/AAA_ml/data/"
  wsi:        "/nb_projects/AAA_ml/data/WSI/"
  train:      "/nb_projects/AAA_ml/data/training/"
  val:        "/nb_projects/AAA_ml/data/validation/"
  test:       "/nb_projects/AAA_ml/data/testing/"
  analysis:   "/nb_projects/AAA_ml/data/analysis"
  models:     "/nb_projects/AAA_ml/models/"
  weights:    "/nb_projects/AAA_ml/weights/"
  logs:       "/nb_projects/AAA_ml/logs/"
  results:    "/nb_projects/AAA_ml/results/"
  grid:       "/nb_projects/AAA_ml/talos/"
  val_list:
    - "3295 5V AAA WEIGERT - 2020-02-27 17.20.54"
    - "4458 5V AAA WEIGERT - 2020-02-27 18.29.59"

class_map:
  None:     0
  Ignore*:  1
  Zone 1:   2
  Zone 2:   3
  Thrombus: 4
  Background: 5

class_colors:
  0: [180, 180, 180]
  1: [180, 180, 180]
  2: [  0,   0, 255]
  3: [  0, 255,   0]
  4: [255,   0,   0]
  5: [139,  21, 166]

active_labels: [0, 1, 2, 3, 4, 5]
ignore_cls: null # change back to 1 if necessary

stats:
  train_m: [216.62469449, 204.54379355, 207.21439871] # Data set mean
  train_s: [29.14629049, 47.60279847, 37.28980667] # Data set standard deviation
  pred_m: [220.08576063, 206.87617786, 224.27487422] # Analysis data set mean
  pred_s: [37.6808387 , 52.17449858, 49.02556889] # Analysis data set standard deviation
  x_min:   [1., 1., 1.] # Data set minimum value - always zero for 8-bit
  x_max:   [242., 235., 240.] # Data set maximum value - always 255 for 8-bit

input_meta:
  x: &x 384
  y: &y 384
  channels: &ch 3
  tile_size: [*x, *y] # Tile dimension in pixels
  shape: &shape [null, null, *ch]

# deep learning model
batch_size: &batch_size 16
nb_epoch: &nb_epoch 100
nb_frozen: &nb_frozen 0
verbose: &verbose 0
drop: &drop 0 # Dropout

# model_kwargs
statics:
  shape: *shape
  nb_epoch: *nb_epoch
  #nb_frozen: *nb_frozen
  nb_filters_0: 32 # Base number of filters
  batch_size: *batch_size
  verbose: *verbose
  num_cls: 6
  batchnorm: True
  maxpool: false
  #date: *date
  opt: "adam"
  depth: 3
  arch: "U-Net"
  dropout: *drop
  decay: 0.0
  sigma_noise: 0.01 # Gaussian noise strength
  act: 'swish'
  pretrain: 1
  lr: 1.0e-4
  class_weights: False
  loss_func: "jaccard2_loss"
  init: "he_normal"


grid_params:
  #dropout: [0]
  #decay: [0.0]
  #lr: [1e-3, 1e-4, 1e-5]
  #sigma_noise: [0]
  nb_filters_0: [12, 16, 32, 64]
  depth: [2, 3, 4]
  #class_weights: [True, False]
  loss_func: ["tversky_loss"] #, "cat_CE", "cat_FL"]
  arch: ["U-Net"]
  act: ["swish"] #, "relu"]
  opt: ["adam",]
  init: ["he_normal",] # "glorot_uniform"]
